kpu:
  swagger:
    version: '@project.version@'
  nacos:
    ip: ${NACOS_IP:@nacos.ip@}
    port: ${NACOS_PORT:@nacos.port@}
    namespace: ${NACOS_NAMESPACE:@nacos.namespace@}
    username: ${NACOS_USERNAME:@nacos.username@}
    password: ${NACOS_PASSWORD:@nacos.password@}
    group: DEFAULT_GROUP
  seata:
    ip: ${SEATA_IP:@seata.ip@}
    port: ${SEATA_PORT:@seata.port@}
    namespace: ${SEATA_NAMESPACE:@seata.namespace@}
  sentinel:
    dashboard: ${SENTINEL_DASHBOARD:@sentinel.dashboard@}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: '@project.artifactId@'
    # kpu自定义配置，用于kpu-scan-starter扫描接口时，拼接uri前缀。 需要和网关配置的前缀一致
    path: /system
  profiles:
    active: '@profile.active@'
  config:
    import:
      - nacos:common.yml?group=${kpu.nacos.group}&refresh=true
      - nacos:redis.yml?group=${kpu.nacos.group}&refresh=true
      - nacos:@database.type@?group=${kpu.nacos.group}&refresh=true
      - nacos:rabbitmq.yml?group=${kpu.nacos.group}&refresh=true
      - nacos:${spring.application.name}.yml?refresh=true
  cloud:
    sentinel:
      enabled: true
      filter:
        enabled: true
      eager: true  # 取消Sentinel控制台懒加载
      transport:
        dashboard: ${kpu.sentinel.dashboard}
    nacos:
      server-addr: ${kpu.nacos.ip}:${kpu.nacos.port}
      username: ${kpu.nacos.username}
      password: ${kpu.nacos.password}
      config:
        file-extension: yml
        namespace: ${kpu.nacos.namespace}
        enabled: true
      discovery:
        namespace: ${kpu.nacos.namespace}
        metadata: # 元数据，用于权限服务实时获取各个服务的所有接口
          management.context-path: ${server.servlet.context-path:}${spring.mvc.servlet.path:}${management.endpoints.web.base-path:}
          gray_version: lmx

# 用于/actuator/info
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'

## 请在nacos中新建一个名为: kpu-openapi-server.yml 的配置文件，并将： kpu-openapi-server/src/main/resources/application.yml 配置文件的内容移动过去
## 然后在项目文件中，删除此文件！！！

dubbo:
  protocol:
    name: dubbo
    port: -1
  application:
    qos-enable: false
  # 提供方
  provider:
    validation: jvalidationNew
  # 消费方
  consumer:
    check: false
    validation: jvalidationNew
  # 注册中心
  registry:
    # 确保 kpu-openapi-server 和 sop-gateway-server 服务的dubbo注册到同一个nacos
    address: nacos://${kpu.nacos.username}:${kpu.nacos.password}@${kpu.nacos.ip}:${kpu.nacos.port}?namespace=${kpu.nacos.namespace}

    check: false
