spring:
  cloud:
    gateway:
      routes:
        # 从这里开始复制
        - id: openapi
          uri: lb://kpu-openapi-server
          predicates:
            - Path=/openapi/**
          filters:
            - StripPrefix=1

## 将配置文件的内容复制到：kpu-gateway-server.yml
## 然后删除本文件！！！
