# 相当于 rabbitmq.yml
kpu:
  rabbitmq:
    # 若系统中有除了zipkin之外的地方使用了mq ，则一定不能设置成false
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: 'kpu'
    password: 'kpu'

spring:
  rabbitmq:
    enabled: ${kpu.rabbitmq.enabled}
    host: ${kpu.rabbitmq.ip}
    port: ${kpu.rabbitmq.port}
    username: ${kpu.rabbitmq.username}
    password: ${kpu.rabbitmq.password}
    listener:
      type: direct # simple direct