<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.lmx.kpu</groupId>
        <artifactId>kpu-dependencies-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../kpu-dependencies-parent/pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>cn.lmx.kpu</groupId>
    <artifactId>kpu-shop</artifactId>
    <name>${project.artifactId}</name>
    <description>商城服务</description>
    <packaging>pom</packaging>

    <modules>
        <module>kpu-shop-facade</module>
        <module>kpu-shop-server</module>
        <module>kpu-shop-entity</module>
        <module>kpu-shop-biz</module>
        <module>kpu-shop-controller</module>
    </modules>
</project>
