kpu:
  cache:
    type: REDIS
  redis:
    ip: 1Panel-redis-RKi2
    port: 6379
    password: 'lmx123125'
    database: 7

spring:
  cache:
    type: GENERIC
  data:
    redis:
      host: ${kpu.redis.ip}
      password: ${kpu.redis.password}
      port: ${kpu.redis.port}
      database: ${kpu.redis.database}
