kpu:
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: 'kpu'
    password: 'kpu'
  cache:
    type: REDIS
  redis:
    ip: 127.0.0.1
    port: 16379
    database: 0
    password: lmx123125
  mysql:
    ip: 127.0.0.1
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: kpu_none
    username: 'root'
    password: 'lmx123125.'
    url: jdbc:mysql://${kpu.mysql.ip}:${kpu.mysql.port}/${kpu.mysql.database}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
